planetjekyll/awesome-jekyll-plugins

- README.md
> Added jekyll-polyglot

- README.md
A plugin for generating UML diagrams using PlantUML tool.
Thx.
> Add jekyll-plantuml plugin

- README.md
Algolia is a super customisable and fast search engine with an easy to use plugin for jekyll
> Add Algolia in 'Search'

- README.md
Please consider adding Premonition to the list.
> Premonition

- README.md
https://github.com/ashmaroli/jekyll-manager
> Add jekyll-manager

- README.md
I've added my plugin: Jekyll PDF Embed
> Added jekyll-pdf-embed

- README.md
> add jekyll-pig

- README.md
Add gem 'jekyll-news-sitemap' to Awesome Jekyll List.
https://github.com/skatkov/jekyll-news-sitemap
> Add gem jekyll-news-sitemap

- README.md
I have moved Premonition from amedia to lazee on Github as I am no longer working for Amedia, and they allowed the move.
> Premonition has moved

- README.md
Add [`jekyll-loading-lazy`](https://github.com/gildesmarais/jekyll-loading-lazy).
> Add jekyll-loading-lazy

- README.md
The plugin jekyll-language-plugin was listed twice in the README.md
> Removed duplicate and update stars

- README.md
🔦Add a new plugin to other section.
> docs: add a new plugin called jekyll-spaceship

- README.md
This PR adds jekyll-imgix to this list of awesome components ✨ This is an awesome library because it makes images rendered by it automatically more performant, and responsive! The repository has been around for years, is well-documented, and commercially-supported. It is a commercial library, but it has a very generous free tier which is enough for most people.
> add jekyll-imgix

- README.md
Update jekyll-spaceship plugin.
> docs: update jekyll-spaceship plugin

- README.md
🔨  Add jekyll-deploy-action for deploying Github Pages.
> docs: add jekyll-deploy-action to deploy section

- README.md
🔨  docs: update jekyll-spaceship and jekyll-deploy-action.
> docs: update jekyll-spaceship and jekyll-deploy-action

- README.md
> Add jekyll-postfiles and jekyll-datapage-generator

- README.md
🎉 Update [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship) plugin information.
Thanks and regards.
> Update jekyll-spaceship plugin

- README.md
This commit is for updating jekyll-spaceship plugin regularly
> docs: update jekyll-spaceship plugin regularly

- README.md
This commit is for updating jekyll-deploy-action regularly.
> docs: update jekyll-deploy-action regularly

- README.md
This is a regular update on jekyll-spaceship.
> chore: update jekyll-spaceship information

- README.md
> Correct the Multiple Languages Plugin information

- README.md
Update jekyll-spaceship information regularly.
> docs: update jekyll-spaceship information

- README.md
Regularly update `jekyll-deploy-action` information
> feat: update jekyll-deploy-action information

- README.md
Regularly update `jekyll-spaceship` information.
> Regularly update jekyll-spaceship information

- README.md
- add Jekyll HTTP Request to other catagory
> docs: add jekyll-http-request

- README.md
Changed premonition ranking according to the RubyGems stats.
> Premonition ranking
